name: Backend Checks

on:
  push:
    tags:
    - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Going to directory
      run: cd backend;
    - name: Building and running tests
      - ./mvnw clean install;
