name: Backend Works

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: ansible check with debian:latest
      uses: roles-ansible/check-ansible-debian-latest-action@master
      with:
        targets: "./"
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Building and running tests
      run: cd backend; ./mvnw clean install
