name: Frontend Works

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: ansible check with debian:latest
      uses: roles-ansible/check-ansible-debian-latest-action@master
      with:
        targets: "./"
    - name: Set up Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Installing Dependencies
      run: cd frontend; yarn install
    - name: Building
      run: cd frontend; yarn build
    - name: Test
      run: cd frontend; yarn test
