name: Frontend Checks

on:
  push:
    branches: [ feature/CICD ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Going to direcctory
      run: cd frontend
    - name: Installing Dependencies
      run: yarn install
    - name: Building
      run: yarn build
    - name: Test
      run: yarn test
